[package]
name = "rmatrix"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.20.0"
getopts = "0.2.21"
rand = "0.8.4"


[profile.release]
codegen-units = 1
lto = "thin"
